# Generated by Django 4.1 on 2025-02-12 13:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Atividade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=500)),
                ("tempo", models.IntegerField(default=10)),
                (
                    "coordenadores",
                    models.ManyToManyField(
                        related_name="coordenadores", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
