# Generated by Django 4.1 on 2025-02-13 15:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0003_remove_atividade_tempo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="atividade",
            name="coordenadores",
        ),
        migrations.AddField(
            model_name="atividade",
            name="responsaveis",
            field=models.ManyToManyField(
                related_name="responsaveis", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
